### ISSUE TITLE
If no events defined, server crashes on boot

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/unchained#371]
```
W20210609-12:00:46.462(2)? (STDERR) (node:17585) UnhandledPromiseRejectionWarning: Error: Enum type EventType must define one or more values.
W20210609-12:00:46.462(2)? (STDERR)     at assertValidSchema (/Users/pozylon/Repositories/publicare-website/engine/node_modules/graphql/type/validate.js:71:11)
W20210609-12:00:46.462(2)? (STDERR)     at assertValidExecutionArguments (/Users/pozylon/Repositories/publicare-website/engine/node_modules/graphql/execution/execute.js:136:35)
W20210609-12:00:46.462(2)? (STDERR)     at executeImpl (/Users/pozylon/Repositories/publicare-website/engine/node_modules/graphql/execution/execute.js:86:3)
W20210609-12:00:46.463(2)? (STDERR)     at Object.execute (/Users/pozylon/Repositories/publicare-website/engine/node_modules/graphql/execution/execute.js:64:63)
W20210609-12:00:46.463(2)? (STDERR)     at Object.generateSchemaHash (/Users/pozylon/Repositories/publicare-website/engine/node_modules/apollo-server-core/dist/utils/schemaHash.js:15:32)
W20210609-12:00:46.463(2)? (STDERR)     at ApolloServer.generateSchemaDerivedData (/Users/pozylon/Repositories/publicare-website/engine/node_modules/apollo-server-core/dist/ApolloServer.js:407:41)
W20210609-12:00:46.463(2)? (STDERR)     at new ApolloServerBase (/Users/pozylon/Repositories/publicare-website/engine/node_modules/apollo-server-core/dist/ApolloServer.js:204:41)
W20210609-12:00:46.463(2)? (STDERR)     at new ApolloServer (/Users/pozylon/Repositories/publicare-website/engine/node_modules/apollo-server-express/dist/ApolloServer.js:60:9)
W20210609-12:00:46.463(2)? (STDERR)     at packages/unchained:api/createGraphQLServer.js:40:18
W20210609-12:00:46.463(2)? (STDERR)     at startUnchainedServer (packages/unchained:api/api.ts:65:31)
W20210609-12:00:46.463(2)? (STDERR)     at packages/unchained:platform/platform.js:50:3
W20210609-12:00:46.463(2)? (STDERR)     at /Users/pozylon/.meteor/packages/promise/.0.11.2.ir23xi.z4mtd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20210609-12:00:46.463(2)? (STDERR)  => awaited here:
W20210609-12:00:46.463(2)? (STDERR)     at Function.Promise.await (/Users/pozylon/.meteor/packages/promise/.0.11.2.ir23xi.z4mtd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
W20210609-12:00:46.463(2)? (STDERR)     at api/index.js:33:3
W20210609-12:00:46.463(2)? (STDERR)     at /Users/pozylon/.meteor/packages/promise/.0.11.2.ir23xi.z4mtd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20210609-12:00:46.463(2)? (STDERR)  => awaited here:
W20210609-12:00:46.464(2)? (STDERR)     at Function.Promise.await (/Users/pozylon/.meteor/packages/promise/.0.11.2.ir23xi.z4mtd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
W20210609-12:00:46.464(2)? (STDERR)     at boot.js:95:3
W20210609-12:00:46.464(2)? (STDERR)     at /Users/pozylon/.meteor/packages/promise/.0.11.2.ir23xi.z4mtd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20210609-12:00:46.464(2)? (STDERR) (node:17585) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by pozylon** [comment]
False positive...
