### ISSUE TITLE
Post-Refactoring Issues

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/unchained#407]
Remaining issues:
- [x] Filter changes sometimes don't trigger a cache invalidation, check the diff
- [x] Do assortment link/children/product changes trigger an invalidation? check the diff
- [x] dropped or missing $text index on product texts
- [x] duplicate _id errors when bulk importing (create for deleted _id, check create mutations and add removal before)
- [x] support alias credential storage on 1st checkout for postfinance
- [x] compatibility with newest meteor version
- [x] loaded filter options don't work anymore, product id cache for filters broken completely
- [x] during import, we try to distinguish the "type" of a media, if we can't it breaks api

Postponed to 1.1:
- Event Types and emit consistency, + especially events for Users
- Deletion Markers

Tested:
- Mutation.loginWithPassword without TOTP
- Mutation.resetPassword
- Mutation.setPassword
- Mutation.changePassword
- Mutation.addEmail
- Mutation.removeEmail
- Mutation.verifyEmail
- Mutation.updateUserProfile
- Mutation.addCartProduct
- All mutations/queries to manage system entities (countries, countries, providers, language)
- Query.users including guests
- Query.user
- Query.me
- Mutation.addCartProduct
- Mutation.addMultipleCartProducts
- Mutation.publishProduct
- Mutation.unpublishProduct
- Mutation.updateProduct
- Mutation.updateProductTexts
- Mutation.updateProductWarehousing
- Mutation.updateProductSupply
- Mutation.updateProductCommerce
- Mutation.reorderAssortmentLinks
- Mutation.addAssortmentLink
- Mutation.removeAssortmentLink
- Mutation.removeAssortmentProduct
- Query.translatedProductTexts
- Query.product
- Query.shopInfo
- Query.productCatalogPrices
- Mutation.updateAssortment
- Query.assortment
- Query.translatedAssortmentTexts
- Mutation.updateAssortmentTexts
- Mutation.createFilter
- Query.translatedFilterTexts
- Query.filter
- Mutation.removeFilterOption
- Mutation.createFilterOption
- Mutation.updateFilterTexts
- Mutation.updateFilter
- Query.users
- Mutation.setUserTags
- Mutation.setRoles
- Query.products
- Mutation.createProduct
- Mutation.createProductVariation
- Mutation.updatePaymentProvider
- Mutation.updateDeliveryProvider
- Query.paymentProvider
- Query.paymentProviders
- Query.deliveryProviders
- Query.deliveryProvider
- Query.warehousingProviders
- Query.warehousingProvider
- Mutation.updateWarehousingProvider
- Mutation.removeProductVariation
- Mutation.createProductVariation
- Query.translatedProductVariationTexts
- Mutation.removeProductVariation
- Mutation.publishProduct
- Mutation.addProductAssignment
- Mutation.createProductVariationOption
- Query.translatedProductVariationTexts
- Mutation.updateProductVariationTexts
- Mutation.removeProductAssignment
- Mutation.addCartProduct with proxy and configs (resolve to simple)
- Query.translatedAssortmentTexts
- Query.assortment
- Mutation.createAssortment
- Query.assortments
- Mutation.updateAssortmentTexts
- Mutation.updateAssortment
- Mutation.addAssortmentProduct
- Mutation.reorderAssortmentProducts
- Mutation.removeAssortmentProduct
- Mutation.setBaseAssortment
- Mutation.addAssortmentLink
- Mutation.removeAssortmentLink
- Query.filters
- Mutation.createFilter
- Query.filter
- Query.translatedFilterTexts
- Mutation.updateFilterTexts
- Mutation.updateFilter
- Mutation.createFilterOption
- Mutation.removeFilterOption
- Mutation.removeFilter
- Mutation.removeAssortment
- Mutation.addAssortmentFilter
- Mutation.removeAssortmentFilter
- Query.orders
- Query.order
- Mutation.removeOrder

TODO:
- Test if all Events emitted
- Test all product, user and assortments fields to return correct data

**Comment by pozylon** [comment]
Old implementation of addProductItem helper which is called from addCartProduct, addMultipleCartProducts, enrollment.generatorOrder, order.addQuotationItem.
```
addProductItem({ product, quantity, configuration, ...rest }) {
    const resolvedProduct = product.resolveOrderableProduct({
      quantity,
      configuration,
    });
    const orderPosition = OrderPositions.upsertPosition({
      orderId: this._id,
      productId: resolvedProduct._id,
      originalProductId: product._id,
      quantity,
      configuration,
      ...rest,
    });
    emit('ORDER_ADD_PRODUCT', { orderPosition });
    return orderPosition;
  },
```

**Comment by pozylon** [comment]
- Query.users
- Mutation.setUserTags
- Mutation.setRoles

**Comment by pozylon** [comment]
- Mutation.updatePaymentProvider
- Mutation.updateDeliveryProvider
- Query.paymentProvider
- Query.paymentProviders
- Query.deliveryProviders
- Query.deliveryProvider
- Query.warehousingProviders
- Query.warehousingProvider
- Mutation.updateWarehousingProvider

**Comment by pozylon** [comment]
- Query.products
- Mutation.createProduct
- Mutation.createProductVariation

**Comment by pozylon** [comment]
https://github.com/unchainedshop/unchained/pull/425 fixes the callback registering issue

**Comment by pozylon** [comment]
- [ ] dropped or missing $text index on product texts

**Comment by pozylon** [comment]
Update:
- Unchained Website is migrated to 1.0 rc.3
- Orderly works with Connector and GridFS on 1.0 rc.3

**Comment by pozylon** [comment]
```

[dev:engine] W20220316-22:43:32.442(1)? (STDERR) (node:34466) UnhandledPromiseRejectionWarning: TypeError: Cannot assign to read only property 'then' of object '#<Promise>'
[dev:engine] W20220316-22:43:32.442(1)? (STDERR)     at _clone (/Users/pozylon/.meteor/packages/unchained_core-events/.1.0.0-rc.9.120rkc9.0d1x++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/clone/clone.js:162:16)
[dev:engine] W20220316-22:43:32.442(1)? (STDERR)     at _clone (/Users/pozylon/.meteor/packages/unchained_core-events/.1.0.0-rc.9.120rkc9.0d1x++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/clone/clone.js:162:18)
[dev:engine] W20220316-22:43:32.442(1)? (STDERR)     at _clone (/Users/pozylon/.meteor/packages/unchained_core-events/.1.0.0-rc.9.120rkc9.0d1x++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/clone/clone.js:162:18)
[dev:engine] W20220316-22:43:32.443(1)? (STDERR)     at clone (/Users/pozylon/.meteor/packages/unchained_core-events/.1.0.0-rc.9.120rkc9.0d1x++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/clone/clone.js:202:10)
[dev:engine] W20220316-22:43:32.443(1)? (STDERR)     at clean (/Users/pozylon/.meteor/packages/unchained_core-events/.1.0.0-rc.9.120rkc9.0d1x++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/simpl-schema/dist/clean.js:64:60)
[dev:engine] W20220316-22:43:32.443(1)? (STDERR)     at SimpleSchema.clean (/Users/pozylon/.meteor/packages/unchained_core-events/.1.0.0-rc.9.120rkc9.0d1x++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/simpl-schema/dist/SimpleSchema.js:845:30)
[dev:engine] W20220316-22:43:32.443(1)? (STDERR)     at packages/unchained:utils/src/db/generate-db-mutations.ts:38:29
[dev:engine] W20220316-22:43:32.443(1)? (STDERR)     at /Users/pozylon/.meteor/packages/promise/.0.12.0.1ckhqvm.h25ij++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
[dev:engine] W20220316-22:43:32.443(1)? (STDERR)  => awaited here:
[dev:engine] W20220316-22:43:32.443(1)? (STDERR)     at Function.Promise.await (/Users/pozylon/.meteor/packages/promise/.0.12.0.1ckhqvm.h25ij++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
[dev:engine] W20220316-22:43:32.443(1)? (STDERR)     at packages/unchained:core-events/src/module/configureEventHistoryAdapter.ts:12:9
[dev:engine] W20220316-22:43:32.443(1)? (STDERR)     at /Users/pozylon/.meteor/packages/promise/.0.12.0.1ckhqvm.h25ij++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
[dev:engine] W20220316-22:43:32.443(1)? (STDERR) (Use `node --trace-warnings ...` to show where the warning was created)
[dev:engine] W20220316-22:43:32.443(1)? (STDERR) (node:34466) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
[dev:engine] W20220316-22:43:32.444(1)? (STDERR) (node:34466) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[dev:engine] W20220316-22:43:32.489(1)? (STDERR) (node:34466) UnhandledPromiseRejectionWarning: TypeError: Cannot assign to read only property 'then' of object '#<Promise>'
[dev:engine] W20220316-22:43:32.489(1)? (STDERR)     at _clone (/Users/pozylon/.meteor/packages/unchained_core-events/.1.0.0-rc.9.120rkc9.0d1x++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/clone/clone.js:162:16)
[dev:engine] W20220316-22:43:32.489(1)? (STDERR)     at _clone (/Users/pozylon/.meteor/packages/unchained_core-events/.1.0.0-rc.9.120rkc9.0d1x++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/clone/clone.js:162:18)
[dev:engine] W20220316-22:43:32.489(1)? (STDERR)     at _clone (/Users/pozylon/.meteor/packages/unchained_core-events/.1.0.0-rc.9.120rkc9.0d1x++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/clone/clone.js:162:18)
[dev:engine] W20220316-22:43:32.489(1)? (STDERR)     at clone (/Users/pozylon/.meteor/packages/unchained_core-events/.1.0.0-rc.9.120rkc9.0d1x++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/clone/clone.js:202:10)
[dev:engine] W20220316-22:43:32.489(1)? (STDERR)     at clean (/Users/pozylon/.meteor/packages/unchained_core-events/.1.0.0-rc.9.120rkc9.0d1x++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/simpl-schema/dist/clean.js:64:60)
[dev:engine] W20220316-22:43:32.489(1)? (STDERR)     at SimpleSchema.clean (/Users/pozylon/.meteor/packages/unchained_core-events/.1.0.0-rc.9.120rkc9.0d1x++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/simpl-schema/dist/SimpleSchema.js:845:30)
[dev:engine] W20220316-22:43:32.490(1)? (STDERR)     at packages/unchained:utils/src/db/generate-db-mutations.ts:38:29
[dev:engine] W20220316-22:43:32.490(1)? (STDERR)     at /Users/pozylon/.meteor/packages/promise/.0.12.0.1ckhqvm.h25ij++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
[dev:engine] W20220316-22:43:32.490(1)? (STDERR)  => awaited here:
[dev:engine] W20220316-22:43:32.491(1)? (STDERR)     at Function.Promise.await (/Users/pozylon/.meteor/packages/promise/.0.12.0.1ckhqvm.h25ij++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
[dev:engine] W20220316-22:43:32.491(1)? (STDERR)     at packages/unchained:core-events/src/module/configureEventHistoryAdapter.ts:12:9
[dev:engine] W20220316-22:43:32.491(1)? (STDERR)     at /Users/pozylon/.meteor/packages/promise/.0.12.0.1ckhqvm.h25ij++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by pozylon** [comment]
now fully compatible with meteor 2.6.1 and thus with mongodb 5
