### ISSUE TITLE
error - TypeError: Cannot read properties of undefined (reading 'locale')

### ISSUE THREAD

**Issue by SohelKabir** [unchainedshop/unchained#496]
Just tried to install storefront after running engine successfully got this error in storefront when i visit localhost:3000 

```
error - pages\_app.tsx (17:40) @ UnchainedApp
error - TypeError: Cannot read properties of undefined (reading 'locale')
    at UnchainedApp (webpack-internal:///./pages/_app.tsx:31:43)
    at processChild (D:\Nanoid\Ecommerce\unchained\FullStackUnchnained\storefront\node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14)
    at resolve (D:\Nanoid\Ecommerce\unchained\FullStackUnchnained\storefront\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (D:\Nanoid\Ecommerce\unchained\FullStackUnchnained\storefront\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (D:\Nanoid\Ecommerce\unchained\FullStackUnchnained\storefront\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToString (D:\Nanoid\Ecommerce\unchained\FullStackUnchnained\storefront\node_modules\react-dom\cjs\react-dom-server.node.development.js:4298:27)
    at Object.renderPage (D:\Nanoid\Ecommerce\unchained\FullStackUnchnained\storefront\node_modules\next\dist\server\render.js:662:46)
    at Object.defaultGetInitialProps (D:\Nanoid\Ecommerce\unchained\FullStackUnchnained\storefront\node_modules\next\dist\server\render.js:332:67)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:21:20)    at Function.getInitialProps (webpack-internal:///./pages/_document.jsx:16:89) {
  page: '/'
}
  15 | 
  16 | const UnchainedApp = ({ Component, pageProps, router }) => {
> 17 |   const messages = localizations[router.locale];
     |                                        ^
  18 | 
  19 |   const toggleCart = (val) => {
  20 |     // eslint-disable-next-line no-use-before-define```

**Comment by Mikearaya** [comment]
Hi @SohelKabir,

Thank you for contributing to unchained. I have replicated the issue locally and added a patch to fix this, please try to do a new initialization of @unchainedshop `npm init @unchainedshop`  or [clone the repo](https://github.com/unchainedshop/storefront)  if you want to get the latest version of the storefront.

Please let us know if you have any further issues.

**Comment by SohelKabir** [comment]
@Mikearaya it's solved. Thanks.
