### ISSUE TITLE
error in Docker build in minimal

### ISSUE THREAD

**Issue by demSly** [unchainedshop/unchained#77]
Hi, I am using Meteor 1.8.1 and I am trying to use the provided Dockerfile, but I am getting an error:
```
$ meteor --version
Meteor 1.8.1
```

```
$ cd examples/minimal/
$ docker build .
Sending build context to Docker daemon  350.7kB
Step 1/22 : FROM pozylon/meteor-docker-auto as bundler
 ---> 704f05487600
Step 2/22 : ADD . /source
 ---> Using cache
 ---> 4d9ca08c4ec7
Step 3/22 : WORKDIR /source
 ---> Using cache
 ---> 08793f16362f
Step 4/22 : RUN meteor npm install &&   meteor build --server-only --allow-superuser --directory /bundle
 ---> Running in bc86fd24b17f

> bcrypt@3.0.6 install /source/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[bcrypt] Success: "/source/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote

> core-js@3.1.4 postinstall /source/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js-pure@3.1.4 postinstall /source/node_modules/core-js-pure
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> protobufjs@6.8.8 postinstall /source/node_modules/protobufjs
> node scripts/postinstall

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 901 packages from 590 contributors and audited 14246 packages in 26.929s
found 7 vulnerabilities (1 low, 6 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local

/root/.meteor/packages/meteor-tool/.1.8.1.ani1yi.p0f9s++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

TypeError: Cannot read property 'filter' of null
    at filterDirectoryContents (/tools/fs/watch.js:309:19)
    at readDirectory (/tools/fs/watch.js:328:10)
    at Object.readAndWatchDirectory (/tools/fs/watch.js:754:18)
    at /tools/packaging/catalog/catalog-local.js:285:41
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.8.1.ani1yi.p0f9s++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/packaging/catalog/catalog-local.js:284:9
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at LocalCatalog._computeEffectiveLocalPackages (/tools/packaging/catalog/catalog-local.js:263:18)
    at LocalCatalog.initialize (/tools/packaging/catalog/catalog-local.js:118:10)
    at /tools/project-context.js:708:29
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/project-context.js:700:20
    at /tools/packaging/catalog/catalog.js:100:5
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._initializeCatalog (/tools/project-context.js:699:13)
    at /tools/project-context.js:300:9
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:290:18)
    at Profile.run (/tools/project-context.js:282:12)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:281:13)
    at /tools/cli/commands.js:971:20
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at Object.main.captureAndExit (/tools/cli/main.js:275:29)
    at buildCommand (/tools/cli/commands.js:968:8)
    at Profile.run (/tools/cli/commands.js:909:25)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at Promise.asyncApply (/tools/cli/commands.js:907:18)
    at /root/.meteor/packages/meteor-tool/.1.8.1.ani1yi.p0f9s++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/root/.meteor/packages/meteor-tool/.1.8.1.ani1yi.p0f9s++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at /tools/cli/main.js:1530:15
The command '/bin/sh -c meteor npm install &&   meteor build --server-only --allow-superuser --directory /bundle' returned a non-zero code: 1
```

**Comment by pozylon** [comment]
@demSly thanks for posting this issue. The reason is the Dockerfile commands ADD/COPY + symbolic links which don't like each other. https://github.com/moby/moby/issues/6094

I usually build the project in a CI with a little trick to make this work:

https://github.com/moby/moby/issues/6094#issuecomment-54556720
